### ISSUE TITLE
[feature-request] update m3u8 and ipfs hash dynamically

### ISSUE THREAD

**Issue by vaultec81** [moshisushi/hlsjs-ipfs-loader#12]
Hello, I am working on a ipfs based live streaming protocol. in order for the client to interface with the player there needs to be a way to dynamically update m3u8 and ipfs hash. Either through a call back or promise API, for the provider functions are registered with hls ipfs loader. After every file request hls ipfs loader should call the API for new updates. (the protocol I'm working on itself will handle updating new m3u8 files and ipfs hashes). Without any apis set or live mode enabled hls ipfs loader will default to static hash.

Related: #5 
I will work on this myself. Just wondering other people's thoughts.

**Comment by moshisushi** [comment]
Definitely something I'm interested in researching as well. It feels like this would truly make use of IPFS' potential as a CDN replacement :)

A quick thought on this: as far as i know, HLS in live stream mode will download the manifest before every segment load, meaning that instead of a static m3u8 file, it now represents a sort of moving window of segments. This is of course requires m3u8 to be a mutable file reference... I haven't researched IPFS MFS at all but perhaps it could be used for this? Mutable manifest, immutable segments.

**Comment by vaultec81** [comment]
@moshisushi AFAIK there is also an option in HLS live to request manifest after a certain set of segments, rather than every segment. A note on this. IPFS MFS is not *actually* mutable. It's a way to interact with your local IPFS repo in a way that seems mutable. The protocol for Livestreaming will handle mutability of manifest. (However I am in preliminary research for building a truly mutable file system)

**Comment by moshisushi** [comment]
Right, gotcha! So, if manifest updates are received over pub sub, the client could cache the latest update in memory, and our hlsjs "fetch manifest" custom function would simply return the cached manifest back to hlsjs, or something along those lines?

**Comment by vaultec81** [comment]
@moshisushi yes, exactly.

**Comment by vaultec81** [comment]
Feature merged, will review before pushing npm update.
